# full documentation at:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# --- what's the name of the workflow?
name: PGENTests

# --- when the workflow starts running?
on: [push]

# --- what does the workflow do?
jobs:
  # it executes tests.
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: [6.0.x]
        
    # ogni step ha un nome e richiede di usare qualche pacchetto o altre robe
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    #- name: Install dependencies
    #  run: dotnet install test
    #  
    #- name: Build
    #  run: dotnet build --no-restore
    #  
    - name: Test
      run: dotnet test #--no-build --verbosity normal