# full documentation at:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# --- what's the name of the workflow?
name: PGENTests

# --- when the workflow starts running?
on: [push]

# --- what does the workflow do?
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: [5.0.x]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal